  main = ".open-next/worker.js"
  name = "rick-and-morty-v2"
  compatibility_date = "2025-12-12"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"